modelname: asymov
_target_: temos.model.asymov.Asymov

vocab_size: ${data.vocab_size}
latent_dim: 256
vae: true

# transforms: ${transforms}

ff_size: 1024
num_layers: 6
num_head: ${model.num_layers}
droupout: 0.1
activation: "gelu"

defaults:
  - textencoder: distilbert_actor
  - motionencoder: asymov
  - motiondecoder: asymov
  - losses: asymov
  - optim: adamw
  - /model/losses/function/crossEntropy@func_recons
  - /model/losses/function/smoothL1@func_latent
  - /model/losses/function/kl@func_kl
